### ISSUE TITLE
Nintendo 3DS port request

### ISSUE THREAD

**Issue by RetroGamer02** [skynettx/raptor#12]
Any chance we could get a Nintendo 3DS port there is already one for Tyrian I would love one for Raptor.

**Comment by RetroGamer02** [comment]
I'm attempting to port it myself wish me luck!

**Comment by skynettx** [comment]
Cool;-)

I'm not familiar with the 3ds homebrew sdk's, but from what I could find out they only support the SDL1.2.
It's just a certain amount of effort to port the project back to SDL1.2, but it's certainly doable.
Opentyrian uses the SDL1.2 which of course simplifies the whole thing.

I will definitely follow your progress with interest.

**Comment by RetroGamer02** [comment]
Gonna try SDL1.2 trying to get the outdated 3DS SDL2 lib to work is well not working out so well.
Edit: Graphics are kinda working on my 3DS port. Getting a weird quadrupling effect of the image.

**Comment by RetroGamer02** [comment]
Porting it to 3DS is going kinda well here's a video of my progress. No working input yet though.
https://www.youtube.com/watch?v=PWKFi2BBx4g

**Comment by skynettx** [comment]
Great work so far!

**Comment by RetroGamer02** [comment]
> Great work so far!

Thank you!
I added music if its running on a new model 3DS.
https://www.youtube.com/watch?v=YVMfK0pfzp4&t=47s

**Comment by RetroGamer02** [comment]
Working Input now but found out it crashes when trying to load a player save and crashes on real hardware in general.

**Comment by RetroGamer02** [comment]
Hi it seems loading or displaying the Bonus Sheds seem to crash the real 3DS hardware but I can't find what part of the code does the loading it does not seem to be ENEMY_DisplayGround or ENEMY_DisplaySky. I don't suppose you know do you?

**Comment by skynettx** [comment]
Oh sorry, I misunderstood yesterday. 
But you were absolutely right the Bonus Sheds are loaded by the ENEMY_DisplayGround function.

**Comment by RetroGamer02** [comment]
Ground shadows out of screen bounds caused the one crash. There's some other kinda random things crashing it as well.

**Comment by RetroGamer02** [comment]
I think I can close this now lol.
