### ISSUE TITLE
GLB_InitSystem passes wrong value

### ISSUE THREAD

**Issue by RetroGamer02** [skynettx/raptor#13]
It passes 6 for a1 which makes it look for FILE0005.GLB which does not exist.

**Comment by skynettx** [comment]
The function is called correctly as in the original raptor.
But if you want to change that, modify the GLB_InitSystem call in rap.cpp as follows:
`GLB_InitSystem(argv[0], 6, 0);` in `GLB_InitSystem(argv[0], 5, 0);`

**Comment by skynettx** [comment]
I saw that you committed the fix and consider the problem solved.
