### ISSUE TITLE
Setup INI Read out of bounds

### ISSUE THREAD

**Issue by RetroGamer02** [skynettx/raptor#14]
INI file being read out of bounds seems to be somewhere in the first prefapi.cpp INI_OpenFile fgets.

**Comment by skynettx** [comment]
What do you mean exactly with read out of bounds?

**Comment by RetroGamer02** [comment]
When run through the 3DS emulator Citra it spews this out in the log.
[  38.501200] Service.FS <Error> core/hle/service/fs/file.cpp:Read:74: Reading from out of bounds offset=0x0 length=0x00000400 file_size=0x50
[  38.512706] Service.FS <Error> core/hle/service/fs/file.cpp:Read:74: Reading from out of bounds offset=0x0 length=0x00000400 file_size=0x50
I reduced the amount of get pref calls and the size of the setup but through testing it does correspond to the SETUP.INI
I think its saying that its read past the end of the file somehow.

**Comment by skynettx** [comment]
I think this is a platform specific issue.
And that results in a crash?

**Comment by RetroGamer02** [comment]
I have not been able to test it proper on a real 3DS yet there is a unrelated crash on real hardware.
Perhaps it does not need changing but I figured I would bring it up.

**Comment by RetroGamer02** [comment]
Should have closed this ages ago.
