### ISSUE TITLE
Reason behind 32bit libs?

### ISSUE THREAD

**Issue by wel97459** [skynettx/raptor#2]
What's was the reason behind choosing 32bit libs?

**Comment by skynettx** [comment]
I see that you have already answered your own question.
I have test your fork on Linux 64 bit and Windows 64 bit with gcc and msvc.
On both systems, with both compilers runs the 64 bit build fine.
All i can say great work!

**Comment by wel97459** [comment]
Thanks, it was a fun puzzle had to debug the UI file format, and notice that the pointer for the texture was miss-aligning the data.
Been working on memory errors so the game is less likely to crash.
