### ISSUE TITLE
@fork wel97459/raptor Win64 build crashing in dspapi 

### ISSUE THREAD

**Issue by skynettx** [skynettx/raptor#3]
Win64 build is crashing in dspapi.cpp void DSP_Mix line 161:
`l += chan->voltable1[(uint8_t)*chan->data];`
Build crashed with chan->data read access violation.
I was only able to trigger this bug under Win64, with msvc and mingw32 and only in 64 bit build.
Under Linux on two different machines, i ran the demo loop for three hours and no crash occurred.
To trigger the bug run the demo loop on Windows, sooner or later the crash will be triggered.
Rarely that the complete demo loop runs through without crashing.
The crash is triggered in the demo loop and also in gameplay when the wave outro is loaded.
I think the problem has something to do with the size of the pointer in 64 bit.
In any case, this has nothing to do with the ALSA implementation, I triggered this bug before.
Good job with the ALSA implementation by the way, sounds great on Linux.

**Comment by wel97459** [comment]
i'll look into the pointer issue, I've seen it once myself.
I used the original game playing in dosbox and fluidsynth debug to compare midi messages and figured out what was going on.  But notice later that the opl2 code had all answers. oh well.
Love the music in this game, and its even better with GM.

**Comment by wel97459** [comment]
I looked into the issue, seems the files related to the FX DSP stuff are mostly all 0 byte files.
and fall into the case on fx.cpp:658 case 0 and the function return -1;
I don't see a issue with any pointers going from 32 to 64.
The issue maybe coming from the struct dsp_t data array in dspapi.h:7 that acts as a pointer at dspapi.cpp:312.
I need to do a little more digging into the FX files and see if I can fine one that has data in it.

**Comment by skynettx** [comment]
As mentioned above i was never able to trigger the bug under Linux.
Yesterday I played through the entire game on Linux without a single crash.
In my opinion, this is a platform-specific bug that only occurs under Win64.
Have you ever been able to trigger the bug on Linux?

**Comment by wel97459** [comment]
No I haven't had any issues in Linux.
But I have had it crash in windows like your talking.
Maybe we could do some type of check for a null pointer.
Before the dspapi.cpp void DSP_Mix line 161.

**Comment by wel97459** [comment]
I think maybe I found the issue in dspapi.cpp:312 the chan->data pointer was set with an offset of 16 from the dsp->data pointer and I don't believe that's needed. 
The header of the FX files uses 8 byte and the data pointer is offset already to the end of that header area.

**Comment by skynettx** [comment]
I tried your fix, build still crashes.
Today I switched off the memory manager in the 32 bit build (glbapi.cpp `vmem=1` to `vmem=0`) to test whether everything is stable, the crash occurs exactly the same in the 32bit build.
If the memory manager is switched on, the build runs absolutely stable.
Without memory manager there are a lot of other crashes in the build (regardless of whether it is 32bit or 64bit).
For example in the demo.cpp void DEMO_GLBFile, rarely but sooner or later the build crashes.
I think the solution to all problems is a 64 bit compatible vmemapi.

**Comment by wel97459** [comment]
I found the issue for real this time.
The SDL Audio Callback thread was trying to access the data for the sounds in the DSP_Mix,  but at the end of game/demo RAP_FreeMap calls "GLB_FreeAll" which frees all loaded files in memory and then it calls SND_CacheIFX which loaded them back into memory.  But during that small amount of time it could crash at DSP_Mix:161.

I've added a check for fx_loaded in the Callback before it calls DSP_Mix.
This will only help stop the crash some what,  and real fix is to add thread locking before checking the value of fx_loaded.

I also found the issue of why the Dumb Missile didn't work right and fixed them, before they would just go to either side of the player, and never went forward after a seconds like they should.

**Comment by skynettx** [comment]
Tested demo loop, has been running for 3 hours without being able to detect a crash.
I modified the vmemapi.cpp so that it runs in the 64-bit environment, and then I couldn't find any more crashes either.
But of course, it's better to fix the bugs directly for a clean one and stable codebase.
I didn't even notice the issue with the Dumb Missile.
All in all great work!
