### ISSUE TITLE
@fork wel97459/raptor Variable renaming issues in the swdapi.cpp

### ISSUE THREAD

**Issue by skynettx** [skynettx/raptor#4]
There are some variable renaming issues in the swdapi.cpp that breaks the cursor control when usekb_flag = 0,
so if control is set to mouse or joystick.
To fix it rename in the swdapi.cpp some ints from Selected to Selectable in line:
```
925
944
968
2156
```

**Comment by wel97459** [comment]
I pushed a fixed. 
Thanks for doing the testing.

I hang out in discord if you want add me.

**Comment by skynettx** [comment]
I'm not on discord, but I'll deal with that in the near future.
