### ISSUE TITLE
I found a lib for better midi support

### ISSUE THREAD

**Issue by wel97459** [skynettx/raptor#5]
This could be a better option for supporting midi on more platforms.

[https://github.com/thestk/rtmidi](https://github.com/thestk/rtmidi)

**Comment by skynettx** [comment]
In any case, a multi-platform solution for midi is the best idea.
This lib might also be an option:

https://github.com/jonof/jfaudiolib

**Comment by skynettx** [comment]
I added TinySoundFont in commit https://github.com/skynettx/raptor/commit/08752f1fa779d34c2e0b017af24cb76294b1171f for Midi support on Windows, Linux and macOS. 

You can switch between system midi (currently only Windows Multimedia) and TinySoundFont with sys_midi=1 or sys_midi=0 in the SETUP.INI config file. 

Copy a soundfont in the sf2 format to raptor directory and rename it to `SoundFont.sf2`. A small soundfont `TimGM6mb.sf2` is in the include folder but for a better quality I recommend the `FluidR3_GM.sf2`.
